# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='req',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('header', django.contrib.postgres.fields.jsonb.JSONField()),
                ('body', models.TextField()),
                ('tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'req',
            },
        ),
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restag', to='database.req')),
            ],
            options={
                'db_table': 'res',
            },
        ),
    ]
